# -*- coding: utf-8 -*-
"""ml final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TmhV-0pc-oRf9d0h1q0Nkb50PU2a0Zqc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

sns.set(style="whitegrid")

# from google.colab import drive
# drive.mount('/content/drive')

df = pd.read_csv('Mall_Customers.csv')
df.head()

print("Shape:", df.shape)
print("\nInfo:\n")
print(df.info())
print("\nMissing/duplicates:", df.duplicated().sum())
df.describe()

sns.pairplot(data=df, hue='Gender')
plt.show()

plt.figure(figsize=(4,4))
sns.countplot(x='Gender', data=df)
plt.show()

plt.figure(figsize=(16,4))
for i, col in enumerate(['Age', 'Annual Income (k$)', 'Spending Score (1-100)']):
    plt.subplot(1, 3, i+1)
    sns.histplot(df[col], bins=10, kde=True)
    plt.title(f"Distribution of {col}")
plt.tight_layout()
plt.show()

X2 = df.iloc[:, -2:]

km_inertias, km_scores = [], []
for k in range(2, 11):
    km = KMeans(n_clusters=k, n_init=10, random_state=42).fit(X2)
    km_inertias.append(km.inertia_)
    km_scores.append(silhouette_score(X2, km.labels_))

plt.figure(figsize=(10,4))
sns.lineplot(x=range(2, 11), y=km_inertias)
plt.title('Elbow Method (Inertia vs k)')
plt.show()

plt.figure(figsize=(10,4))
sns.lineplot(x=range(2, 11), y=km_scores)
plt.title('Silhouette Score vs k')
plt.show()

X3 = df.iloc[:, -3:]

km_inertias, km_scores = [], []
for k in range(2, 11):
    km = KMeans(n_clusters=k, n_init=10, random_state=42).fit(X3)
    km_inertias.append(km.inertia_)
    km_scores.append(silhouette_score(X3, km.labels_))

plt.figure(figsize=(10,4))
sns.lineplot(x=range(2, 11), y=km_inertias)
plt.title('Elbow Method (Inertia vs k)')
plt.show()

plt.figure(figsize=(10,4))
sns.lineplot(x=range(2, 11), y=km_scores)
plt.title('Silhouette Score vs k')
plt.show()

km = KMeans(n_clusters=5, n_init=10, random_state=42).fit(X3)

plt.figure(figsize=(10,6))
sns.scatterplot(x=X3.iloc[:, 1], y=X3.iloc[:, 2], hue=km.labels_, palette="Set2")
plt.scatter(km.cluster_centers_[:,1], km.cluster_centers_[:,2], c='black', s=200, marker='X', label='Centroids')
plt.legend()
plt.show()

plt.figure(figsize=(10,6))
sns.scatterplot(x=X3.iloc[:, 0], y=X3.iloc[:, 1], hue=km.labels_, palette="Set2")
plt.scatter(km.cluster_centers_[:,0], km.cluster_centers_[:,1], c='black', s=200, marker='X')
plt.show()

from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(111, projection='3d')

xs = X3.iloc[:, 0]
ys = X3.iloc[:, 1]
zs = X3.iloc[:, 2]
ax.scatter(xs, ys, zs, c=km.labels_, s=50, alpha=0.7)

centers = km.cluster_centers_
ax.scatter(centers[:,0], centers[:,1], centers[:,2], c='black', s=300, marker='X')

ax.set_xlabel('Age')
ax.set_ylabel('Annual Income (k$)')
ax.set_zlabel('Spending Score (1-100)')
plt.show()

X3['label'] = km.labels_

cluster_summary = X3.groupby('label').mean()
print("Cluster Summary (mean values):\n")
print(cluster_summary)

cluster_names = {
    0: "Older low Income Low Spenders",
    1: "Moderate Balanced",
    2: "Young High Income Hign Spenders",
    3: "High Income but Frugal",
    4: "Young Low Income High Spenders"
}

print("\nCluster Interpretation:\n")
for k in cluster_summary.index:
    print(f"Cluster {k} → {cluster_names.get(k, 'Undefined')}")
    print(cluster_summary.loc[k])
    print("\n")